// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_GHG_cpp
Rcpp::List compute_GHG_cpp(const arma::mat& G, const arma::mat& Hhalf);
RcppExport SEXP _GLOWr_compute_GHG_cpp(SEXP GSEXP, SEXP HhalfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Hhalf(HhalfSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_GHG_cpp(G, Hhalf));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GLOWr_compute_GHG_cpp", (DL_FUNC) &_GLOWr_compute_GHG_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_GLOWr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
