# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute GHG Matrix for Score Variance
#'
#' Efficiently computes the score variance matrix GHG = G'G - G'H H'G
#' using Armadillo linear algebra library.
#'
#' @param G Numeric matrix (n x p): Genotype or weighted genotype matrix
#' @param Hhalf Numeric matrix (n x k): H^(1/2) projection matrix
#'
#' @return List with components:
#'   \item{GHG}{Matrix (p x p): Score variance matrix}
#'   \item{GHhalf}{Matrix (p x k): Intermediate product G' H^(1/2)}
#'
#' @details
#' This function computes:
#'   GtG = G' * G
#'   GHhalf = G' * H^(1/2)
#'   GHG = GtG - GHhalf * GHhalf'
#'
#' The C++ implementation provides 2-5x speedup over pure R implementation.
#'
#' @keywords internal
compute_GHG_cpp <- function(G, Hhalf) {
    .Call(`_GLOWr_compute_GHG_cpp`, G, Hhalf)
}

